(()=>{'use strict';
const STORAGE_KEY='hebrew_srs_items_v2_verbs',SETTINGS_KEY='hebrew_srs_settings_v2_verbs',intervals=[1,2,4,8,16,32,64,128];let items=[],queue=[],current=null;const $=id=>document.getElementById(id);
const formLabels={pr_ms:'наст. м. ед.',pr_fs:'наст. ж. ед.',pr_mp:'наст. м. мн.',pr_fp:'наст. ж. мн.',pa_1s:'прош. я',pa_1p:'прош. мы',pa_2ms:'прош. ты м.',pa_2fs:'прош. ты ж.',pa_2mp:'прош. вы м.',pa_2fp:'прош. вы ж.',pa_3ms:'прош. он',pa_3fs:'прош. она',pa_3p:'прош. они',fu_1s:'буд. я',fu_1p:'буд. мы',fu_2ms:'буд. ты м.',fu_2fs:'буд. ты ж.',fu_2p:'буд. вы',fu_3ms:'буд. он',fu_3fs:'буд. она',fu_3p:'буд. они'};
const present=['pr_ms','pr_fs','pr_mp','pr_fp'],past=['pa_1s','pa_1p','pa_2ms','pa_2fs','pa_2mp','pa_2fp','pa_3ms','pa_3fs','pa_3p'],future=['fu_1s','fu_1p','fu_2ms','fu_2fs','fu_2p','fu_3ms','fu_3fs','fu_3p'],allVerbKeys=[...present,...past,...future];
function todayISO(){const d=new Date();d.setHours(0,0,0,0);return d.toISOString().slice(0,10)}function addDaysISO(days){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}function uid(){return'i_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2)}function getMode(){return document.querySelector('input[name="mode"]:checked')?.value||'single'}function getDirection(){return document.querySelector('input[name="direction"]:checked')?.value||'ru-to-translit'}function due(item){return!item.nextReview||item.nextReview<=todayISO()}
function normalize(item){if(item.type==='verb')return{id:item.id||uid(),type:'verb',title:String(item.title||'').trim(),tags:String(item.tags||'').trim(),forms:item.forms||{},comment:String(item.comment||'').trim(),level:Number(item.level||0),misses:Number(item.misses||0),created:item.created||todayISO(),lastReview:item.lastReview||'',nextReview:item.nextReview||todayISO()};return{id:item.id||uid(),type:'single',russian:String(item.russian||'').trim(),translit:String(item.translit||'').trim(),tags:String(item.tags||'').trim(),comment:String(item.comment||'').trim(),level:Number(item.level||0),misses:Number(item.misses||0),created:item.created||todayISO(),lastReview:item.lastReview||'',nextReview:item.nextReview||todayISO()}}
function load(){try{items=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(!Array.isArray(items))items=[];items=items.map(normalize).filter(x=>x.type==='verb'?x.title:(x.russian&&x.translit))}catch{items=[];alert('Не удалось прочитать базу.')}try{const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');if(s.mode)document.querySelector(`input[name="mode"][value="${s.mode}"]`)?.click();if(s.direction)document.querySelector(`input[name="direction"][value="${s.direction}"]`)?.click()}catch{}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(items));updateStats()}function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify({mode:getMode(),direction:getDirection()}))}
function updateStats(){$('dueCount').textContent=items.filter(due).length;$('totalCount').textContent=items.length;$('knownCount').textContent=items.filter(i=>(i.level||0)>=3).length;$('missCount').textContent=items.reduce((s,i)=>s+(Number(i.misses)||0),0)}
function buildQueue(){saveSettings();const mode=getMode();queue=items.filter(i=>due(i)&&i.type===mode).sort((a,b)=>String(a.nextReview||'').localeCompare(String(b.nextReview||'')));nextCard()}
function verbSummary(v){return `${allVerbKeys.filter(k=>v.forms&&v.forms[k]).length} форм`}
function nextCard(){current=queue.shift()||null;$('answerBox').classList.add('hidden');if(!current){$('reviewCard').classList.add('hidden');$('emptyReview').classList.remove('hidden');updateStats();return}$('emptyReview').classList.add('hidden');$('reviewCard').classList.remove('hidden');const dir=getDirection();if(current.type==='verb'){$('front').textContent=current.title||'глагол';$('answerMain').textContent=verbSummary(current);$('answerDetails').innerHTML=renderVerbTable(current);$('cardMeta').textContent=`${current.tags||'без тегов'} · глагол · уровень ${current.level||0} · ошибок ${current.misses||0}`}else{const front=dir==='ru-to-translit'?current.russian:current.translit,answer=dir==='ru-to-translit'?current.translit:current.russian;$('front').textContent=front||'—';$('answerMain').textContent=answer||'—';$('answerDetails').innerHTML=`<div class="kv"><b>Русский:</b> ${esc(current.russian||'—')}</div><div class="kv"><b>Транслитерация:</b> ${esc(current.translit||'—')}</div><div class="kv"><b>Теги:</b> ${esc(current.tags||'—')}</div><div class="kv"><b>Комментарий:</b> ${esc(current.comment||'—')}</div>`;$('cardMeta').textContent=`${current.tags||'без тегов'} · карточка · уровень ${current.level||0} · ошибок ${current.misses||0}`}}
function renderVerbTable(v){const row=k=>`<tr><td class="label">${esc(formLabels[k])}</td><td class="form">${esc(v.forms?.[k]||'—')}</td></tr>`;return`<div class="kv"><b>Теги:</b> ${esc(v.tags||'—')}</div><div class="kv"><b>Комментарий:</b> ${esc(v.comment||'—')}</div><table class="verb-table"><tr><th colspan="2">Настоящее время</th></tr>${present.map(row).join('')}<tr><th colspan="2">Прошедшее время</th></tr>${past.map(row).join('')}<tr><th colspan="2">Будущее время</th></tr>${future.map(row).join('')}</table>`}
function showAnswer(){$('answerBox').classList.remove('hidden')}function grade(ok){if(!current)return;const item=items.find(i=>i.id===current.id);if(!item)return;if(ok){item.level=Math.min((item.level||0)+1,intervals.length-1);item.nextReview=addDaysISO(intervals[item.level])}else{item.level=0;item.misses=(item.misses||0)+1;item.nextReview=addDaysISO(1)}item.lastReview=todayISO();save();nextCard()}function skip(){if(current)queue.push(current);nextCard()}
function addSingle(){const russian=$('russianInput').value.trim(),translit=$('translitInput').value.trim();if(!russian||!translit)return alert('Заполни русский смысл и транслитерацию.');items.push(normalize({type:'single',russian,translit,tags:$('tagsInput').value.trim(),comment:$('commentInput').value.trim()}));$('russianInput').value='';$('translitInput').value='';$('commentInput').value='';save();buildQueue();renderList()}
function parseLine(line,tags){const raw=line.trim();if(!raw)return null;if(raw.includes('|')){const p=raw.split('|').map(x=>x.trim());if(p[0]&&p[1])return normalize({type:'single',russian:p[0],translit:p[1],tags:p[2]||tags,comment:p[3]||''})}let p=raw.split(/\t+/).map(x=>x.trim()).filter(Boolean);if(p.length<2)p=raw.split(/\s{2,}/).map(x=>x.trim()).filter(Boolean);if(p.length>=2)return normalize({type:'single',russian:p[0],translit:p.slice(1).join(' '),tags});return null}
function bulkAdd(){const text=$('bulkInput').value,tags=$('bulkTagsInput').value.trim();if(!text.trim())return;let added=0,skipped=0;for(const line of text.split(/\r?\n/)){const c=parseLine(line,tags);if(!c){if(line.trim())skipped++;continue}items.push(c);added++}$('bulkInput').value='';save();buildQueue();renderList();alert(`Добавлено: ${added}`+(skipped?`\nПропущено: ${skipped}`:''))}
function collectVerbFromFields(){const title=$('verbTitleInput').value.trim();if(!title){alert('Нужно название/перевод глагола.');return null}const forms={};for(const k of allVerbKeys){const val=$(k)?.value.trim();if(val)forms[k]=val}if(!Object.keys(forms).length){alert('Нужно заполнить хотя бы одну форму.');return null}return normalize({type:'verb',title,tags:$('verbTagsInput').value.trim(),forms,comment:$('verbCommentInput').value.trim()})}
function clearVerbFields(){$('verbTitleInput').value='';$('verbTagsInput').value='';$('verbCommentInput').value='';for(const k of allVerbKeys)if($(k))$(k).value=''}function addVerb(){const v=collectVerbFromFields();if(!v)return;items.push(v);clearVerbFields();save();buildQueue();renderList()}
function addVerbBulk(){const text=$('verbBulkInput').value.trim();if(!text)return;const data={forms:{}};for(const line of text.split(/\r?\n/)){if(!line.trim()||!line.includes('|'))continue;const[keyRaw,...rest]=line.split('|'),key=keyRaw.trim(),val=rest.join('|').trim();if(!val)continue;if(key==='title')data.title=val;else if(key==='tags')data.tags=val;else if(key==='comment')data.comment=val;else if(allVerbKeys.includes(key))data.forms[key]=val}if(!data.title)return alert('В тексте нужна строка: title | перевод глагола');if(!Object.keys(data.forms).length)return alert('Нет форм глагола.');items.push(normalize({type:'verb',...data}));$('verbBulkInput').value='';save();buildQueue();renderList();alert('Глагол добавлен.')}
function esc(s){return String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}function match(item,q){const blob=item.type==='verb'?[item.title,item.tags,item.comment,...Object.values(item.forms||{})].join(' '):[item.russian,item.translit,item.tags,item.comment].join(' ');return blob.toLowerCase().includes(q)}function filtered(){const q=$('searchInput').value.trim().toLowerCase();return q?items.filter(i=>match(i,q)):items}
function renderList(){const data=filtered().slice().sort((a,b)=>String(a.type==='verb'?a.title:a.russian).localeCompare(String(b.type==='verb'?b.title:b.russian)));if(!data.length){$('list').innerHTML='<p class="muted">Ничего нет.</p>';return}$('list').innerHTML=data.map(i=>i.type==='verb'?`<div class="item"><div class="title">Глагол: ${esc(i.title)}</div><div class="meta">${esc(i.tags||'без тегов')} · ${verbSummary(i)} · следующее: ${esc(i.nextReview||'сегодня')} · уровень ${i.level||0} · ошибок ${i.misses||0}</div>${renderVerbTable(i)}<button data-action="reset" data-id="${esc(i.id)}">Сбросить</button><button data-action="due" data-id="${esc(i.id)}">На сегодня</button><button class="danger" data-action="delete" data-id="${esc(i.id)}">Удалить</button></div>`:`<div class="item"><div class="title">${esc(i.russian)}</div><div class="form">${esc(i.translit)}</div><div class="meta">${esc(i.tags||'без тегов')} · следующее: ${esc(i.nextReview||'сегодня')} · уровень ${i.level||0} · ошибок ${i.misses||0}</div>${i.comment?`<div class="meta">${esc(i.comment)}</div>`:''}<button data-action="reset" data-id="${esc(i.id)}">Сбросить</button><button data-action="due" data-id="${esc(i.id)}">На сегодня</button><button class="danger" data-action="delete" data-id="${esc(i.id)}">Удалить</button></div>`).join('')}
function listAction(e){const btn=e.target.closest('button[data-action]');if(!btn)return;const item=items.find(i=>i.id===btn.dataset.id);if(!item)return;if(btn.dataset.action==='delete'){if(!confirm('Удалить?'))return;items=items.filter(i=>i.id!==btn.dataset.id)}if(btn.dataset.action==='reset'){item.level=0;item.misses=0;item.nextReview=todayISO()}if(btn.dataset.action==='due')item.nextReview=todayISO();save();buildQueue();renderList()}
function exportData(){const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hebrew-srs-${todayISO()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported))throw new Error();items=imported.map(normalize).filter(x=>x.type==='verb'?x.title:(x.russian&&x.translit));save();buildQueue();renderList();alert(`Импортировано: ${items.length}`)}catch{alert('Не удалось импортировать JSON.')}};reader.readAsText(file)}
function clearAll(){if(!confirm('Удалить всю базу на этом устройстве?'))return;items=[];save();buildQueue();renderList()}
function bind(){$('showAnswerBtn').addEventListener('click',showAnswer);$('knownBtn').addEventListener('click',()=>grade(true));$('unknownBtn').addEventListener('click',()=>grade(false));$('skipBtn').addEventListener('click',skip);$('addBtn').addEventListener('click',addSingle);$('bulkBtn').addEventListener('click',bulkAdd);$('addVerbBtn').addEventListener('click',addVerb);$('addVerbBulkBtn').addEventListener('click',addVerbBulk);$('renderBtn').addEventListener('click',renderList);$('exportBtn').addEventListener('click',exportData);$('importBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',importData);$('clearBtn').addEventListener('click',clearAll);$('searchInput').addEventListener('input',renderList);$('list').addEventListener('click',listAction);document.querySelectorAll('input[name="mode"],input[name="direction"]').forEach(r=>r.addEventListener('change',buildQueue))}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));bind();load();updateStats();buildQueue();
})();